# versão para o docker-compose
version: "3.7"
# quais são os serviços que vamos precisar rodar
services:
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes: 
      - .:/usr/app